version: '3.9'
services:

  zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: ${ZOOKEEPER_CONTAINER_NAME}
    restart: always
    networks:
      - envynet-msg
    volumes:
      - ./${DEV_FOLDER}/zookeeper/data:/bitnami/zookeeper
    ports:
      - ${ZOOKEEPER_PORT}:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: ${ZOOKEEPER_ALLOW_ANONYMOUS_LOGIN}

  kafka:
    image: bitnami/kafka:3.2.1
    container_name: ${KAFKA_CONTAINER_NAME}
    restart: always
    networks:
      - envynet-msg
    volumes:
      - ./${DEV_FOLDER}/kafka/data:/bitnami/kafka
    ports:
      - ${KAFKA_EXT_PORT}:9092
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_CONTAINER_NAME}:${ZOOKEEPER_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      ALLOW_PLAINTEXT_LISTENER: ${KAFKA_ALLOW_PLAINTEXT_LISTENER}
    depends_on:
      - zookeeper

  kowl:
    image: quay.io/cloudhut/kowl
    container_name: ${KOWL_CONTAINER_NAME}
    restart: always
    networks:
      - envynet-msg
    volumes:
      - ./${DEV_FOLDER}/kowl/config.yaml:/etc/kowl/config.yaml
    ports:
      - ${KOWL_PORT}:8080
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    depends_on:
      - kafka

networks:
  envynet-msg:
    driver: bridge
